version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    command: sleep infinity
    volumes:
      - ../:/workspace
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0 # Required if using "mysql_native_password"(See below 👇)
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    # env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_USER=myuser
    # entrypoint: sh -c "/usr/local/bin/docker-entrypoint.sh --default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d # Mount custom init script

  # mongo:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb-data:/data/db
volumes:
  # mongodb-data:
  mysql-data:
